backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img
publish_mode: editorial_workflow

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: Seo de la página, name: seopage, widget: seoPage }
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Fecha de publicación", name: "date", widget: "datetime"}
      - {label: "Descripción", name: "description", widget: "text"}
      - {label: "Post destacado", name: "featuredpost", widget: "boolean", required: false}
      - {label: "Imagen destacada", name: "featuredimage", widget: image}
      - {label: "Contenido", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "impresoras"
    label: "impresoras"
    folder: "src/pages/impresoras"
    path: "{{slug}}/index.md"
    media_folder: '/static/img'
    public_folder: '/static/img'
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "printer-page"}
      - {label: "Nombre de la impresora", name: "title", required: true, widget: "string"}
      - {label: "Imagen destacada", name: "featuredimage", widget: image}
      - {label: "Título de la página (h1)", name: "pageTitle", required: true, widget: "string"}
      - {label: "Enlace de Amazon", name: "amazonLink", widget: "string"}
      - {label: "Enlace de Aliexpress", name: "aliexpressLink", widget: "string"}
      - label: "Enlaces personalizados"
        name: "customLinks"
        widget: "list"
        fields:
          - { label: "Tienda", name: "store", widget: "string", required:true }
          - { label: "link", name: "link", widget: "string", required:true }
      - {label: "Valoración inicial", name: "initialValuation", required: true, widget: "markdown"}
      - label: "Imágenes de producto"
        name: "productsImages"
        widget: "list"
        fields:
          - { label: "Imagen", name: "src", widget: "image", required: true }
          - { label: "Alt Texto", name: "alt", widget: "string", required: true }
      - label: "Creación de secciones"
        name: "customSections"
        widget: "list"
        fields:
          - label: "Color de fondo"
            name: "backgroundColor"
            widget: "select"
            options: ["Claro", "Medio", "Oscuro"]
            default: "Claro"
          - { label: "Título", name: "title", widget: "string" }
          - {label: "Contenido de la sección", name: "sectionContent", required: true, widget: "markdown"}
          - {label: "Mostrar borde inferior", name: "showBorder", widget: "boolean", default: false}
      - label: "Propiedades"
        name: "properties"
        widget: "object"
        fields:
          - {label: "Título", name: "title", widget: "string", required: false}
          - {label: "Contenido inicial", name: "sectionContent", widget: "markdown", required: false}
          - label: "Características"
            name: "feature"
            widget: "object"
            collapsed: true
            fields: 
              - {label: "Tecnología", name: "technology", widget: "select", default: "FDM", options: ["FDM", "Resina"], required: false}
              - {label: "Volumen de impresión", name: "printerVolume", widget: "string", required: false}
              - {label: "Resolución de capa", name: "layerResolution", widget: "string", required: false}
              - {label: "Precisión en los ejes", name: "axisPrecision", widget: "string", required: false}
              - {label: "Número de extrusores", name: "extrusorNumber", widget: "string", required: false}
              - {label: "Extrusor", name: "extrusor", widget: "string", required: false}
              - {label: "Diámetro de filamento", name: "filamentDiameter", widget: "string", required: false}
              - {label: "Diámetro del nozzle", name: "nozzleDiameterList", widget: "string", required: false}
              - {label: "Nivelación de la cama", name: "bedLevel", widget: "select", default: "Manual", options: ["Manual", "autonivelación"]}
              - {label: "Velocidad de impresión", name: "printerSpeed", widget: "string", required: false}
              - {label: "Temperatura máxima del hotend", name: "extrusorTemperature", widget: "string", required: false}
              - {label: "Temperatura máxima de la cama", name: "BedTemperature", widget: "string", required: false}
              - {label: "Materiales soportados", name: "materials", widget: "string", required: false}
          - label: "Software"
            name: "software"
            widget: "object"
            collapsed: true
            fields: 
              - {label: "Slicer", name: "slicer", widget: "string", required: false}
              - {label: "Formatos de entrada", name: "inputFormat", widget: "string", required: false}
              - {label: "Firmware", name: "firmware", widget: "string", required: false}
              - {label: "Display", name: "display", widget: "string", required: false}
              - {label: "Conectividad", name: "conectivity", widget: "string", required: false}
          - label: "Electricidad"
            name: "electricity"
            widget: "object"
            collapsed: true
            fields: 
              - {label: "Capacidad de entrada", name: "input", widget: "string", required: false}
              - {label: "Voltaje", name: "voltage", widget: "string", required: false}
          - label: "Unboxing"
            name: "unboxing"
            widget: "object"
            collapsed: true
            fields: 
              - {label: "Dimensiones de la impresora", name: "printerSize", widget: "string", required: false}
              - {label: "Peso de la impresora", name: "printerWeight", widget: "string", required: false}
              - {label: "Dimensiones del paquete", name: "unboxingSize", widget: "string", required: false}
              - {label: "Peso del paquete", name: "unboxingWeight", widget: "string", required: false}
          - label: "Contenido"
            name: "content"
            widget: "object"
            collapsed: true
            fields: 
              - {label: "Contenido", name: "content", widget: "markdown"}
      - label: "¿Dónde comprar?"
        name: "whereBuy"
        widget: "object"
        collapsed: true
        fields:
          - {label: "Título", name: "title", widget: "string", required: false}
          - {label: "Texto inicial", name: "sectionContent", widget: "markdown", required: false}
          - {label: "Texto de donde comprar", name: "whereBuyText", widget: "markdown", required: false}
      - label: "Ventajas y desventajas"
        name: "advantagesDisadvantajes"
        widget: "object"
        collapsed: true
        fields:
          - {label: "Título", name: "title", widget: "string", required: false}
          - {label: "Texto inicial", name: "sectionContent", widget: "markdown", required: false}
          - label: "Ventajas"
            name: "advantages"
            widget: "list"
            fields:
              - { label: "Texto", name: "text", widget: "markdown" }
          - label: "Desventajas"
            name: "disadvantages"
            widget: "list"
            fields:
              - { label: "Texto", name: "text", widget: "markdown" }
      - label: "Impresiones realizadas con la impresora 3D"
        name: "prints"
        widget: "object"
        collapsed: true
        fields:
          - {label: "Título", name: "title", widget: "string", required: false}
          - {label: "Texto inicial", name: "sectionContent", widget: "markdown", required: false}
          - label: "Imágenes de impresiones"
            name: "printImage"
            widget: "list"
            fields:
              - { label: "Imagen", name: "src", widget: "image", required: true }
              - { label: "Alt Texto", name: "alt", widget: "string", required: true }
      - label: "Mejoras para imprimir"
        name: "upgradesToPrint"
        widget: "object"
        collapsed: true
        fields:
          - {label: "Título", name: "title", widget: "string", required: true}
          - {label: "Texto inicial", name: "sectionContent", widget: "markdown", required: false}
          - label: "Mejora"
            name: "upgrades"
            widget: "list"
            fields:
              - { label: "Texto", name: "text", widget: "string" }
              - { label: "Link", name: "link", widget: "string" }
              - { label: "Imagen", name: "image", widget: "string" }
      - label: "Conclusión final"
        name: "finalValuation"
        widget: "object"
        collapsed: true
        fields:
          - {label: "Título", name: "title", widget: "string", required: true}
          - {label: "Texto inicial", name: "sectionContent", widget: "markdown", required: false}
      - label: "Llamada a la acción"
        name: "callToAction"
        widget: "object"
        collapsed: true
        fields:
          - {label: "Título", name: "title", widget: "string", required: false}
          - {label: "Texto de donde comprar", name: "actionText", widget: "markdown", required: false}
      - {label: "Fecha de publicación", name: "date", widget: "datetime"}
      - {label: "Título SEO", name: "metaTitle", widget: "string", required: true, hint: "campo de texto", pattern: ['^.{1,70}$', "este campo debe de tener un máximo de 70 caracteres"]}
      - {label: "Descripción SEO", name: "metaDescription", widget: "text", required: true, hint: "campo de texto", pattern: ['^.{1,150}$', "este campo debe de tener un máximo de 150 caracteres"]}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "reviews"
    label: "Review"
    folder: "src/pages/reviews"
    create: true
    fields:
      - {label: Template Key, name: templateKey, widget: hidden, default: review-page}
      - {label: Listado de productos, name: productsList, widget: productsList}
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Nombre del producto", name: "name", widget: "string"}
      - {label: "Fecha de publicación", name: "date", widget: "datetime"}
      - {label: "Descripción", name: "description", widget: "text"}
      - {label: "Post destacado", name: "featuredpost", widget: "boolean", required: false}
      - {label: "Imagen destacada", name: "featuredimage", widget: image}
      - {label: "valoración", name: "ratings", widget: "string"}
      - {label: "Contenido", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "pages"
    label: "Páginas"
    files:
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/products/index.md"
        label: "Products Page"
        name: "products"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image}
          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
